<a href="https://colab.research.google.com/github/Akshay-datascience/sample_repo/blob/master/BREAST_CANCER_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Breast_cancer_prediction.csv')
df


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M    14.204716     20.202641          122.80     1001.0   
1      842517         M    18.483496     22.464181          132.90     1326.0   
2    84300903         M    15.516300     18.271486          130.00     1203.0   
3    84348301         M    15.540583     27.560108           77.58      386.1   
4    84358402         M    14.005198     11.678064          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M     9.477218     17.173224          142.00     1479.0   
565    926682         M    11.657306     25.502865          131.20     1261.0   
566    926954         M    20.102883     14.544119          108.30      858.1   
567    927241         M    16.206551     19.616466          140.10     1265.0   
568     92751         B    13.256191     25.087474           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.096113          0.089479        0.184766             0.096526   
1           0.094443          0.063299        0.086927             0.021108   
2           0.075842          0.059376        0.132738             0.052357   
3           0.091525          0.088022        0.194466             0.010895   
4           0.092790          0.010642        0.030518             0.037828   
..               ...               ...             ...                  ...   
564         0.110550          0.037279        0.160806             0.047462   
565         0.113881          0.108912        0.134949             0.039279   
566         0.100213          0.003465        0.072762             0.042914   
567         0.112486          0.158756        0.096860             0.024182   
568         0.110289          0.044248       -0.072171             0.029954   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_wors  concavity_worst  \
0             0.16220          0.134597           0.7119   
1             0.12380          0.529227           0.2416   
2             0.14440          0.166906           0.4504   
3             0.20980          0.224998           0.6869   
4             0.13740          0.075833           0.4000   
..                ...               ...              ...   
564           0.14100          0.238996           0.4107   
565           0.11660          0.219149           0.3215   
566           0.11390          0.279461           0.3403   
567           0.16500          0.116461           0.9387   
568           0.08996          0.389369           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.120681          0.4601                 0.101594  
1                0.035439          0.2750                 0.079397  
2                0.149670          0.3613                 0.088802  
3                0.110799          0.6638                 0.086210  
4                0.126386          0.2364                 0.087483  
..                    ...             ...                      ...  
564              0.163526          0.2060   

In [ ]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M    14.204716     20.202641          122.80     1001.0   
1    842517         M    18.483496     22.464181          132.90     1326.0   
2  84300903         M    15.516300     18.271486          130.00     1203.0   
3  84348301         M    15.540583     27.560108           77.58      386.1   
4  84358402         M    14.005198     11.678064          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0         0.096113          0.089479        0.184766             0.096526   
1         0.094443          0.063299        0.086927             0.021108   
2         0.075842          0.059376        0.132738             0.052357   
3         0.091525          0.088022        0.194466             0.010895   
4         0.092790          0.010642        0.030518             0.037828   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_wors  concavity_worst  concave points_worst  \
0            0.1622          0.134597           0.7119              0.120681   
1            0.1238          0.529227           0.2416              0.035439   
2            0.1444          0.166906           0.4504              0.149670   
3            0.2098          0.224998           0.6869              0.110799   
4            0.1374          0.075833           0.4000              0.126386   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                 0.101594  
1          0.2750                 0.079397  
2          0.3613                 0.088802  
3          0.6638                 0.086210  
4          0.2364                 0.087483  

[5 rows x 32 columns]

In [ ]:
df.tail()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424         M     9.477218     17.173224          142.00     1479.0   
565  926682         M    11.657306     25.502865          131.20     1261.0   
566  926954         M    20.102883     14.544119          108.30      858.1   
567  927241         M    16.206551     19.616466          140.10     1265.0   
568   92751         B    13.256191     25.087474           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564         0.110550          0.037279        0.160806             0.047462   
565         0.113881          0.108912        0.134949             0.039279   
566         0.100213          0.003465        0.072762             0.042914   
567         0.112486          0.158756        0.096860             0.024182   
568         0.110289          0.044248       -0.072171             0.029954   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_wors  concavity_worst  \
564           0.14100          0.238996           0.4107   
565           0.11660          0.219149           0.3215   
566           0.11390          0.279461           0.3403   
567           0.16500          0.116461           0.9387   
568           0.08996          0.389369           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
564              0.163526          0.2060                 0.073780  
565              0.032357          0.2572                 0.068449  
566              0.113976          0.2218                 0.098450  
567              0.067784          0.4087                 0.074609  
568              0.192663          0.2871                 0.062577  

[5 rows x 32 columns]

In [ ]:
df.shape

(569, 32)

In [ ]:
df.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_wors           float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [ ]:
df.isna().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_wors           0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [ ]:
df.drop(['id'],axis=1,inplace=True)

In [ ]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['diagnosis']=lab.fit_transform(df['diagnosis'])
df['diagnosis']

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [ ]:
df.dtypes

diagnosis                    int64
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_wors           float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [ ]:
x=df.iloc[:,:-1].values
x

array([[ 1.        , 14.2047163 , 20.20264101, ...,  0.7119    ,
         0.12068091,  0.4601    ],
       [ 1.        , 18.48349635, 22.46418139, ...,  0.2416    ,
         0.03543911,  0.275     ],
       [ 1.        , 15.51629953, 18.2714859 , ...,  0.4504    ,
         0.14967045,  0.3613    ],
       ...,
       [ 1.        , 20.10288258, 14.54411949, ...,  0.3403    ,
         0.11397573,  0.2218    ],
       [ 1.        , 16.20655056, 19.61646595, ...,  0.9387    ,
         0.06778428,  0.4087    ],
       [ 0.        , 13.25619109, 25.08747393, ...,  0.        ,
         0.19266257,  0.2871    ]])

In [ ]:
y=df.iloc[:,-1].values
y

array([0.10159359, 0.07939726, 0.08880227, 0.08621   , 0.08748291,
       0.05792208, 0.07942798, 0.08253358, 0.09534985, 0.07288521,
       0.08567896, 0.05495896, 0.10794435, 0.09165108, 0.06839052,
       0.05737507, 0.09325592, 0.07728575, 0.10304529, 0.08919181,
       0.0815652 , 0.08745491, 0.08359663, 0.09882642, 0.10067224,
       0.07821549, 0.08814605, 0.05590876, 0.09126709, 0.10966994,
       0.08512817, 0.08419619, 0.09104702, 0.05694108, 0.09668178,
       0.0525917 , 0.05386309, 0.07168329, 0.10506929, 0.09172472,
       0.09395106, 0.08725306, 0.03702681, 0.09369233, 0.07348137,
       0.11473811, 0.05230464, 0.06993914, 0.10378903, 0.07406997,
       0.12243264, 0.08188456, 0.06477738, 0.07439413, 0.05021655,
       0.08063205, 0.07284894, 0.06051292, 0.06856105, 0.0799874 ,
       0.08472186, 0.09467847, 0.08533389, 0.111827  , 0.09216374,
       0.07950384, 0.11033597, 0.06141468, 0.08438342, 0.08136743,
       0.05235424, 0.0642166 , 0.08805059, 0.09505072, 0.07251

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[0.00000000e+00, 1.53875807e+01, 2.38088736e+01, ...,
        1.80400000e-01, 6.55169580e-02, 2.66400000e-01],
       [0.00000000e+00, 1.58753750e+01, 1.47596746e+01, ...,
        1.84500000e-03, 6.30319720e-02, 2.43900000e-01],
       [0.00000000e+00, 1.00754323e+01, 2.05071024e+01, ...,
        2.51200000e-01, 1.38526565e-01, 2.53400000e-01],
       ...,
       [1.00000000e+00, 1.53289591e+01, 2.42037250e+01, ...,
        6.56600000e-01, 1.55897544e-01, 3.31300000e-01],
       [0.00000000e+00, 1.15751425e+01, 1.42580558e+01, ...,
        6.23100000e-02, 8.41022660e-02, 2.22600000e-01],
       [0.00000000e+00, 1.33273184e+01, 1.11651449e+01, ...,
        4.83300000e-02, 2.55697417e-01, 1.98700000e-01]])

In [ ]:
y_train

array([0.08229388, 0.06856105, 0.08581777, 0.07785472, 0.10950639,
       0.09286769, 0.10663618, 0.09177461, 0.09461597, 0.07875887,
       0.06609682, 0.09717127, 0.10581519, 0.07238495, 0.10304529,
       0.06363798, 0.11242111, 0.09852436, 0.06645808, 0.09321882,
       0.08336119, 0.10040407, 0.09844974, 0.06150016, 0.08207504,
       0.05230464, 0.06355591, 0.07084813, 0.05164288, 0.07494383,
       0.07344377, 0.09805814, 0.0869165 , 0.09490464, 0.082595  ,
       0.08906931, 0.10784342, 0.09188351, 0.07586515, 0.07472908,
       0.05644081, 0.06222351, 0.10766876, 0.09953069, 0.1243852 ,
       0.07480261, 0.06263614, 0.08527297, 0.05153488, 0.04687058,
       0.05879977, 0.08475387, 0.08072438, 0.08100235, 0.0711876 ,
       0.0457525 , 0.09882642, 0.0633102 , 0.09165108, 0.0810413 ,
       0.09467847, 0.06533637, 0.07338986, 0.06298463, 0.09172472,
       0.05051096, 0.05235424, 0.10660536, 0.09047312, 0.06243466,
       0.1402628 , 0.05787005, 0.07972673, 0.08874318, 0.07012

In [ ]:
x_test

array([[ 0.00000000e+00,  1.88393282e+01,  2.29049082e+01, ...,
         3.21900000e-01,  1.72833384e-01,  2.82700000e-01],
       [ 1.00000000e+00,  1.15571346e+01,  2.15975188e+01, ...,
         5.00600000e-01,  1.16085807e-01,  3.90000000e-01],
       [ 0.00000000e+00,  1.39179032e+01,  1.17049974e+01, ...,
         2.24100000e-01, -1.18645040e-02,  3.38000000e-01],
       ...,
       [ 1.00000000e+00,  1.38552241e+01,  1.69775011e+01, ...,
         3.96500000e-01,  1.27306519e-01,  3.79200000e-01],
       [ 0.00000000e+00,  1.40079273e+01,  2.29983272e+01, ...,
         1.99200000e-01,  1.35322431e-01,  3.60400000e-01],
       [ 0.00000000e+00,  1.43072968e+01,  1.51390819e+01, ...,
         3.58200000e-02,  8.61739480e-02,  2.97600000e-01]])

In [ ]:
y_test

array([0.06628937, 0.06993914, 0.06535247, 0.05334762, 0.07209967,
       0.07832288, 0.08973714, 0.06612345, 0.06211782, 0.07638878,
       0.08649268, 0.08619356, 0.12069956, 0.08116571, 0.09234591,
       0.1123609 , 0.07149755, 0.07527356, 0.08270501, 0.10860375,
       0.05225624, 0.08277821, 0.08936132, 0.07906029, 0.07950384,
       0.08714818, 0.07146082, 0.07562936, 0.0623128 , 0.12131444,
       0.07378004, 0.04399105, 0.07728575, 0.07064624, 0.11033597,
       0.09037306, 0.06632905, 0.08418975, 0.08725306, 0.06747945,
       0.09556434, 0.07406997, 0.08122646, 0.06580784, 0.07169801,
       0.10427147, 0.09064654, 0.0655283 , 0.09344582, 0.10966994,
       0.11787707, 0.10159359, 0.12019374, 0.07998094, 0.06588316,
       0.06415206, 0.08577819, 0.0631924 , 0.11667436, 0.07549261,
       0.08391698, 0.07288521, 0.04254571, 0.09064267, 0.1349319 ,
       0.08613694, 0.05954213, 0.05939989, 0.08982801, 0.10729878,
       0.09908252, 0.08136743, 0.09395106, 0.05846833, 0.10087

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

ValueError: Unknown label type: (array([0.08229388, 0.06856105, 0.08581777, 0.07785472, 0.10950639,
       0.09286769, 0.10663618, 0.09177461, 0.09461597, 0.07875887,
       0.06609682, 0.09717127, 0.10581519, 0.07238495, 0.10304529,
       0.06363798, 0.11242111, 0.09852436, 0.06645808, 0.09321882,
       0.08336119, 0.10040407, 0.09844974, 0.06150016, 0.08207504,
       0.05230464, 0.06355591, 0.07084813, 0.05164288, 0.07494383,
       0.07344377, 0.09805814, 0.0869165 , 0.09490464, 0.082595  ,
       0.08906931, 0.10784342, 0.09188351, 0.07586515, 0.07472908,
       0.05644081, 0.06222351, 0.10766876, 0.09953069, 0.1243852 ,
       0.07480261, 0.06263614, 0.08527297, 0.05153488, 0.04687058,
       0.05879977, 0.08475387, 0.08072438, 0.08100235, 0.0711876 ,
       0.0457525 , 0.09882642, 0.0633102 , 0.09165108, 0.0810413 ,
       0.09467847, 0.06533637, 0.07338986, 0.06298463, 0.09172472,
       0.05051096, 0.05235424, 0.10660536, 0.09047312, 0.06243466,
       0.1402628 , 0.05787005, 0.07972673, 0.08874318, 0.07012399,
       0.1348054 , 0.07939   , 0.08134354, 0.06155404, 0.12449679,
       0.07939726, 0.11107533, 0.05590876, 0.09229868, 0.0594767 ,
       0.09505072, 0.12151387, 0.09156686, 0.09277895, 0.05818376,
       0.06977488, 0.05769942, 0.10370956, 0.05662453, 0.07674416,
       0.10794435, 0.06989394, 0.06257672, 0.09571899, 0.0802932 ,
       0.09564067, 0.09927187, 0.07300889, 0.09677479, 0.06839052,
       0.10663297, 0.11217494, 0.08357961, 0.08460267, 0.08646885,
       0.08060336, 0.08141066, 0.09484288, 0.08799149, 0.09470012,
       0.08188456, 0.08542165, 0.09775098, 0.13066844, 0.07616401,
       0.09089106, 0.06397079, 0.10003633, 0.08554146, 0.08581241,
       0.07280583, 0.08559059, 0.07875928, 0.10050186, 0.08326128,
       0.10532877, 0.09355949, 0.12556434, 0.07488273, 0.06436387,
       0.05862251, 0.07879481, 0.06537479, 0.07046852, 0.06445418,
       0.10065422, 0.07135041, 0.10689293, 0.11326986, 0.06960156,
       0.09893165, 0.10894916, 0.05503511, 0.08253534, 0.06385672,
       0.08546052, 0.0924595 , 0.08188176, 0.0445406 , 0.07246309,
       0.07017247, 0.08085976, 0.06677977, 0.09005313, 0.08209288,
       0.09486386, 0.07439413, 0.11293924, 0.06723378, 0.07460934,
       0.08293729, 0.05565866, 0.10575946, 0.06398806, 0.07546894,
       0.07348137, 0.10420989, 0.06791516, 0.07100326, 0.08830907,
       0.06992259, 0.09002304, 0.08145488, 0.08990815, 0.12243264,
       0.08478427, 0.09534985, 0.09104702, 0.11184896, 0.0671216 ,
       0.08328362, 0.08421026, 0.08352501, 0.09126709, 0.1069815 ,
       0.0653895 , 0.08063205, 0.07570055, 0.09070729, 0.05350892,
       0.09051551, 0.10378903, 0.09359686, 0.09860043, 0.05694108,
       0.0525917 , 0.08337692, 0.111827  , 0.07646934, 0.07947958,
       0.08605081, 0.08274729, 0.05592284, 0.06844935, 0.08115491,
       0.11473811, 0.06205828, 0.04398657, 0.07518046, 0.0658455 ,
       0.07843227, 0.10071633, 0.08745491, 0.09662403, 0.08782268,
       0.10188278, 0.09119657, 0.08662168, 0.07921741, 0.10067224,
       0.07349661, 0.09567109, 0.09391149, 0.07811567, 0.09619957,
       0.08433631, 0.06971968, 0.07369184, 0.07645787, 0.06686742,
       0.08831586, 0.08928646, 0.05884026, 0.07284894, 0.05218777,
       0.09034735, 0.06681665, 0.12458603, 0.07251885, 0.10156079,
       0.08074986, 0.10880054, 0.07351943, 0.08290677, 0.03995926,
       0.1158439 , 0.11183823, 0.0944268 , 0.12387619, 0.05841017,
       0.05021655, 0.07582096, 0.08910248, 0.09880003, 0.07007998,
       0.08006672, 0.06222497, 0.11859782, 0.07644988, 0.09076947,
       0.06892289, 0.07774592, 0.07751038, 0.06105528, 0.06702781,
       0.08196624, 0.07903387, 0.08472186, 0.10501497, 0.06811562,
       0.09420197, 0.11302737, 0.07557479, 0.09184507, 0.07273453,
       0.05872453, 0.07703502, 0.07822118, 0.06424813, 0.06333784,
       0.08567896, 0.07494306, 0.11796109, 0.06064775, 0.08367432,
       0.06051292, 0.08774922, 0.08670756, 0.09125479, 0.05927311,
       0.05386309, 0.08512817, 0.0815652 , 0.0700395 , 0.06215153,
       0.07794387, 0.09759277, 0.0784984 , 0.09060836, 0.08178876,
       0.09640303, 0.07875981, 0.09262798, 0.08880227, 0.13175736,
       0.09628675, 0.06477738, 0.09325612, 0.06532451, 0.11307998,
       0.09980986, 0.12450667, 0.07610845, 0.05983069, 0.06482871,
       0.10380037, 0.06496583, 0.08218111, 0.09080499, 0.08991976,
       0.0682784 , 0.07251987, 0.08122101, 0.09490947, 0.08899837,
       0.06722453, 0.07229789, 0.07944721, 0.10185116, 0.08125115,
       0.0790177 , 0.10949313, 0.03109037, 0.06476741, 0.04406922,
       0.07661988, 0.10484975, 0.09161381, 0.06467376, 0.06598602,
       0.10324833, 0.09768071, 0.08359663, 0.06408775, 0.06591659,
       0.06779605, 0.07821549, 0.07997791, 0.09216374, 0.05737507,
       0.07010088, 0.11667402, 0.06504045, 0.08814605, 0.09369233,
       0.09971458, 0.08208654, 0.08792167, 0.08602035, 0.0563461 ,
       0.0642166 , 0.0726224 , 0.08505065, 0.05652465, 0.08196205,
       0.07581675, 0.08085816, 0.06187934, 0.07444862, 0.07295775,
       0.08253358, 0.05314373, 0.0730123 , 0.09089348, 0.06679038,
       0.04549298, 0.09112728, 0.06707712, 0.06343778, 0.06732139,
       0.0595405 , 0.09871549, 0.11760232, 0.07769838, 0.03817425,
       0.08723831, 0.11757576, 0.04626565, 0.08137873, 0.0789031 ,
       0.08805059, 0.09972315, 0.07168329]),)

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

NameError: name 'y_pred' is not defined