<a href="https://colab.research.google.com/github/Akshay-datascience/sample_repo/blob/master/Male_female_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('/content/gender_classification.csv')
df

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [6]:
df.columns

Index(['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'gender'],
      dtype='object')

In [7]:
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1    Male  
1          1                          0  Female  
2          1                          1    Male  
3          1                          1    Male  
4          0                          0  Female

In [8]:
df.tail()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male

In [9]:
df.dtypes

long_hair                      int64
forehead_width_cm            float64
forehead_height_cm           float64
nose_wide                      int64
nose_long                      int64
lips_thin                      int64
distance_nose_to_lip_long      int64
gender                        object
dtype: object

In [10]:
df.isna().sum()

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [11]:
x=df.iloc[:,:-1].values
x

array([[ 1. , 11.8,  6.1, ...,  0. ,  1. ,  1. ],
       [ 0. , 14. ,  5.4, ...,  0. ,  1. ,  0. ],
       [ 0. , 11.8,  6.3, ...,  1. ,  1. ,  1. ],
       ...,
       [ 1. , 12.9,  5.7, ...,  0. ,  0. ,  0. ],
       [ 1. , 13.2,  6.2, ...,  0. ,  0. ,  0. ],
       [ 1. , 15.4,  5.4, ...,  1. ,  1. ,  1. ]])

In [12]:
y=df.iloc[:,-1].values
y

array(['Male', 'Female', 'Male', ..., 'Female', 'Female', 'Male'],
      dtype=object)

In [13]:
df.size

40008

In [14]:
df.shape

(5001, 8)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[ 1. , 13. ,  6.4, ...,  0. ,  0. ,  0. ],
       [ 1. , 11.8,  5.1, ...,  0. ,  1. ,  1. ],
       [ 1. , 12. ,  5.5, ...,  1. ,  1. ,  1. ],
       ...,
       [ 1. , 13.4,  5.5, ...,  0. ,  0. ,  0. ],
       [ 1. , 13.7,  5.7, ...,  1. ,  1. ,  1. ],
       [ 1. , 15.1,  5.4, ...,  1. ,  1. ,  1. ]])

In [16]:
x_test

array([[ 1. , 12.8,  6.3, ...,  0. ,  1. ,  0. ],
       [ 1. , 12.3,  5.8, ...,  1. ,  1. ,  1. ],
       [ 1. , 11.5,  5.4, ...,  0. ,  0. ,  0. ],
       ...,
       [ 1. , 11.6,  5.8, ...,  1. ,  1. ,  1. ],
       [ 1. , 13.3,  5.4, ...,  0. ,  1. ,  0. ],
       [ 0. , 13.7,  5.1, ...,  1. ,  1. ,  1. ]])

In [17]:
y_train

array(['Female', 'Female', 'Male', ..., 'Female', 'Male', 'Male'],
      dtype=object)

In [18]:
y_test

array(['Female', 'Male', 'Female', ..., 'Male', 'Female', 'Male'],
      dtype=object)

In [19]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
knn=KNeighborsClassifier(n_neighbors=7)
bayes=GaussianNB()
sup=SVC()
lst=[knn,bayes,sup]



In [21]:
for i in lst:
  print("The model is: ",i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  cm=confusion_matrix(y_test,y_pred)
  print("The confusion_matrix of model:",i, "is: ")
  print(cm)
  score=accuracy_score(y_test,y_pred)
  print("The accuracy_score of model:",i,"is: ")
  print(score)
  cr=classification_report(y_test,y_pred)
  print("The classification_report of model:",i,"is: ")
  print(cr)



The model is:  KNeighborsClassifier(n_neighbors=7)
The confusion_matrix of model: KNeighborsClassifier(n_neighbors=7) is: 
[[731  14]
 [ 36 720]]
The accuracy_score of model: KNeighborsClassifier(n_neighbors=7) is: 
0.966688874083944
The classification_report of model: KNeighborsClassifier(n_neighbors=7) is: 
              precision    recall  f1-score   support

      Female       0.95      0.98      0.97       745
        Male       0.98      0.95      0.97       756

    accuracy                           0.97      1501
   macro avg       0.97      0.97      0.97      1501
weighted avg       0.97      0.97      0.97      1501

The model is:  GaussianNB()
The confusion_matrix of model: GaussianNB() is: 
[[723  22]
 [ 21 735]]
The accuracy_score of model: GaussianNB() is: 
0.9713524317121919
The classification_report of model: GaussianNB() is: 
              precision    recall  f1-score   support

      Female       0.97      0.97      0.97       745
        Male       0.97      0.97

In [22]:
print(i.predict(scaler.transform([[1,10.4,6.3,1,0,0,1]])))

['Male']
